const products = [
  {
            "productId": 46760,
            "name": "1-800-FLOWERS",
            "description": "<p>Gift-giving has never been easier with the 1-800-FLOWERS.COM® Gift Card! Browse a wide selection of fresh flowers, delicious gourmet treats and desserts, beautiful plants, stunning gift baskets and more – and then choose exactly what you want!</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>You can use your eGift Card at any Cheryls® or Harry & David® retail stores and online at www.1800baskets.com, www.1800flowers.com, www.cheryls.com, www.fruitbouquets.com, www.harryanddavid.com, www.stockyards.com, www.thepopcornfactory.com and www.wolfermans.com. Acceptance of this card constitutes acceptance of these terms and conditions, which may change at any time. To view your eGift Card balance, go to&nbsp;<a href=\"http://freshgift.com/\">http://freshgift.com/</a>. This eGift Card does not expire.</p>",
            "expiryAndValidity": "<p>No Expiry</p>",
            "redemptionInstructions": "<p>1. Visit:&nbsp;<a href=\"http://www.1800flowers.com\">www.1800flowers.com</a>&nbsp;and redeem.&nbsp;</p>",
            "categories": "Apparel_Fashion & Accessories",
            "lastUpdateDate": "2023-05-09 15:19:35",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/php6w0JH6_wxmtxg.jpg",
            "currencyCode": "USD",
            "currencyName": "Dollar",
            "countryName": "USA",
            "countryCode": "US",
            "countries": [
              {
                "code": "US",
                "name": "USA"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "10.0000,25.0000,50.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 7,
            "exchangeRate": 83.9446855,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 48772,
            "name": "1-800-PetSupplies",
            "description": "<p>The 1-800-PetSupplies.com staff features some of the leading authorities in the pet world. We are dedicated to you and your pets, creating the best place online to meet others, learn the new and exciting, blog, shop and easily find anything and everything pet related.</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>Terms and Conditions Your acceptance of this eCertificate constitutes your agreement to these terms and conditions. This card is redeemable in U.S. only for merchandise on www.1-800-petsupplies.com. Only two eCertificates are redeemable per order. eCertificates cannot be redeemed for cash, except as required by law. Void if altered or reproduced. This gift card is issued in U.S. funds by Tabcom, LLC. By accepting these Terms and Conditions through your use of this Site, you certify that you reside in the United States and are 18 years of age or older. If you are under the age of 18 but at least 14 years of age you may use this Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms and Conditions. TABcom does not knowingly collect personal information about children under the age of 14 without prior parental consent. If you are a parent or legal guardian agreeing to these Terms and Conditions for the benefit of a child between the ages of 14 and 18, please be advised that you are fully responsible for his or her use of this site, including all financial charges and legal liability that he or she may incur</p>",
            "expiryAndValidity": "<p>No Expiry&nbsp;</p>",
            "redemptionInstructions": "<div><div>Visit the link: <a href=\"http://www.1-800-petsupplies.com\">www.1-800-petsupplies.com</a> on your browser and redeem.</div></div><p>&nbsp;</p>",
            "categories": "Health and Wellness,Work From Home",
            "lastUpdateDate": "2023-05-16 14:10:00",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpI9xySK_wazbqu.jpg",
            "currencyCode": "USD",
            "currencyName": "Dollar",
            "countryName": "USA",
            "countryCode": "US",
            "countries": [
              {
                "code": "US",
                "name": "USA"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "25.0000,50.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 7.5,
            "exchangeRate": 83.9446855,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 51699,
            "name": "2 Degrees Mobile NZ",
            "description": "<p>2 Degrees prepaid mobile top-up voucher.</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>For help at any stage call 0800 022 022 Our Prepay plans just got heaps more choice. Grab one in our App or see the plans at 2dm.co.nz/prepay Want to stretch your data? Download the Data Clock App in the App Store or Google Play to buy unlimited data by the minute, not the megabyte. Please use voucher by the expiry date displayed above. Credit lasts for 365 days on a standard Prepay SIM or 90 days on a NZ Visitor SIM. Voucher is non-refundable and includes GST. For full T&C visit www.2dm.co.nz</p>",
            "expiryAndValidity": "<p>12 Months</p>",
            "redemptionInstructions": "<p>Avail voucher at&nbsp;<a href=\"https://www.2dm.co.nz/plans\">www.2dm.co.nz/plans</a></p>",
            "categories": "Electronics",
            "lastUpdateDate": "2023-05-15 06:04:40",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpp41gy0_qlrhxc.jpg",
            "currencyCode": "NZD",
            "currencyName": "New Zealand Dollar",
            "countryName": "New Zealand",
            "countryCode": "NZ",
            "countries": [
              {
                "code": "NZ",
                "name": "New Zealand"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "20.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 1,
            "exchangeRate": 49.65422297,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 52830,
            "name": "220.lv",
            "description": "<p>If you have ever searched for a magic wand in the 220.lv assortment, then today you have almost found it! Visit the largest shopping center on the Internet 220.lv, choose your favorite products and add them to your wish list, and on September 6, we will randomly select the winner who will receive 500 euros in 220.lv cash! The more items you add to your wish list, the more likely it is that the winner's prize will be credited to your user account. Good luck!</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<ol><li>The gift card can only be used to buy products only sold by&nbsp;<a href=\"http://www.220.lv\">www.220.lv</a>&nbsp;AND NOT FOR PRODUCTS SOLD by 3rd party sellers on market place</li><li>One or more Gift Cards can be used for one single order.</li><li>If the value of the order exceeds the value of the Gift Cards/s, the customer must pay the difference to complete the order.</li><li>The Gift Card can be used ONLY ONCE. Any remaining funds in case the value of a purchase/order is LESS THAN the value of the Gift Card is NOT REFUNDED and CANNOT be used for other purchases/orders.</li><li>The Gift Card can be used to buy one or more products, as long as they are purchased in one purchase/order.</li><li>The amount on the Gift Card must be spent in one purchase.</li><li>There is no cash-back or change-in cash possible.</li><li>Gift voucher will be delivered within 7 to 8 working days.</li></ol>",
            "expiryAndValidity": "<p>12 Months</p>",
            "redemptionInstructions": "<p><span style=\"font-variant-ligatures: normal; orphans: 2; widows: 2;\">Avail voucher at&nbsp;</span><a href=\"https://220.lv/lv/\" style=\"font-variant-ligatures: normal; orphans: 2; widows: 2;\">https://220.lv/lv/</a></p>",
            "categories": "Jewelry & Lifestyle",
            "lastUpdateDate": "2023-08-28 10:23:26",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpVcTSqN_dssyrw.jpg",
            "currencyCode": "EUR",
            "currencyName": "European euro",
            "countryName": "Latvia",
            "countryCode": "LV",
            "countries": [
              {
                "code": "LV",
                "name": "Latvia"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "20.0000,50.0000",
            "tatInDays": "2 - 7",
            "usageType": "",
            "deliveryType": "delayed",
            "fee": 5,
            "discount": 0,
            "exchangeRate": 91.11398567,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 48266,
            "name": "30% OFF on Zee5 12 Months Subscription",
            "description": "<p>TEST GIFT CARD</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>GrabGifts e-voucher can only be used through the Grab app.<br />GrabGifts e-voucher is not a cash voucher.<br />GrabGifts e-voucher is not redeemable for cash or credit.<br />GrabGifts e-voucher will not be replaced/reimbursed if lost, stolen or expired. Grab is not responsible for GrabGifts e-voucher that has been redeemed or misused by anyone other than the intended recipient.<br />GrabGifts e-voucher is valid for 180 days from the date of purchase. GrabGifts e-voucher cannot be reissued/extended after expiry.<br />GrabGifts e-voucher cannot be used to purchase other Grab vouchers.<br />GrabGifts e-voucher can only be used once. Any remaining balance will be forfeited. If the value of your ride exceeds the value of GrabGifts e-voucher, any outstanding balance must be paid using a different payment method.<br />GrabGifts e-voucher cannot be recharged/reloaded.<br />GrabGifts e-voucher cannot be used with other promotions/vouchers/gift e-vouchers in a single ride at the time of booking.<br />GrabGifts e-voucher cannot be cancelled/refunded.<br />GrabGifts e-voucher can only be redeemed via the Grab app and used for Grab Rides only within the country of issuance.<br />After claiming the GrabGifts e-voucher on the Grab app, the GrabGifts e-voucher will be added under the \"My Rewards\" section. To utilise the GrabGifts e-voucher, go under \"My Rewards\" and select the e-voucher at the time of booking.<br />An active and valid Grab account is required to redeem the GrabGifts e-voucher. If app is not available, User will be prompted to download the Grab App from Google Play or Appstore.</p>",
            "expiryAndValidity": "<p>12 Months</p>",
            "redemptionInstructions": "<div><strong>IMPORTANT INSTRUCTIONS</strong></div><div>1. One Gift Cards (Vouchers) CAN be used in one bill.</div><div>2. Gift Cards (Vouchers) CAN be used online.</div><div>3. Partial redemption of the coupon is not allowed.</div><div><strong>HOW TO REDEEM YOUR&nbsp;</strong><strong>GIFT CARDS (VOUCHERS)</strong><strong>?</strong></div><div>1. Go to the website - <a href=\"https://www.zee5.com/\">ZEE5.com</a> or the mobile app.</div><div>2. Register your account with your phone number.</div><div>3. On the payment screen, click on HAVE A PROMO CODE. Enter the Promo Code that you have received after getting the Gift Card.</div><div>4. Click Pay Now to make the payment and enjoy unlimited entertainment on ZEE5.</div><div><strong>HOW TO BUY AN ZEE5&nbsp;</strong><strong>GIFT CARDS (VOUCHERS)</strong><strong>?</strong></div><div>ZEE5 Gift Cards (Vouchers) are available on the <a href=\"https://stores.xoxoday.com/nreach/\">Xoxoday Store website</a>/Mobile application. You can purchase these Gift Cards (Vouchers)&nbsp;by using Net Banking, Credit and Debit Cards.</div><div>1. Visit <a href=\"https://stores.xoxoday.com/nreach/vouchers/description/zee5-12-months-subscription/48266\">Xoxoday Store website/Zee5-12-months-subscription</a>: View and select from the available vouchers of ZEE5.</div><div>2. Select your preferred denominations & checkout: You can choose the denomination/s of your preference from those available.</div><div>3. Pay via Debit/ Credit/ Net Banking or Xoxoday Voucher/Points: Enter your preferred mode of payment and purchase the Gift Voucher/s.</div><div><strong>ZEE5&nbsp;</strong><strong>GIFT CARDS (VOUCHERS)</strong><strong>&nbsp;FOR OCCASIONS</strong></div><div>The gift that shows you care. Your loved ones have always been there for you and gone to great lengths when you needed them to. Now here's something you can do to show how much you care about them. Gift your loved one a ZEE5 GIFT CARD. Watch a movie, play, a match, a stand-up comedy act and many more are available on ZEE5 at a discount. Your loved one can use it for his or her time spending. It's the perfect gift to make a special occasion, even more meaningful.</div><div><strong>ZEE5&nbsp;</strong><strong>GIFT CARDS (VOUCHERS)</strong><strong>&nbsp;FOR CORPORATE GIFTING</strong></div><div>Want to give your clients, partners and employees corporate Diwali presents that they will remember? Give them a ZEE5 GIFT CARD and ensure that they have an unlimited variety of movies and shows in multiple languages. Let your employees know that you care about them and their loved ones.&nbsp;</div><div><strong>HOW TO GET A ZEE5&nbsp;GIFT CARDS (VOUCHERS)&nbsp;</strong><strong>FOR FREE?&nbsp;</strong></div><div>There are multiple ways to get a ZEE5 Gift Cards (Vouchers) for free. You may use loyalty points from your HDFC Solitaire Credit Card, IndusInd Credit Card, BPCL Petro Card or RBL Credit Card to buy an ZEE5 GIFT CARD at no cost.</div><div><strong>FREQUENTLY ASKED QUESTIONS</strong></div><div><strong>How can I return/cancel ZEE5&nbsp;</strong><strong>Gift Cards (Vouchers)&nbsp;</strong><strong>which I have redeemed?</strong></div><div>Regret that it is not possible. Gift Cards (Vouchers) once redeemed/bought cannot be cancelled or returned.</div><div><strong>Can I buy a ZEE5</strong><strong>Gift Cards (Vouchers)&nbsp;</strong><strong>Using my XOXO VOUCHER/POINTS?</strong></div><div>Yes, you can buy a ZEE5 Gift Cards (Vouchers) using XOXO VOUCHER/POINTS.</div><div><strong>How can I know the status of my ZEE5&nbsp;Gift Cards (Vouchers)?</strong></div><div>Yes of course! Enter your voucher code in the Gift Cards (Vouchers) Detail section. You will know the status of your ZEE5 Gift Cards (Vouchers). Alternately, you may also call at +91 80-61915050 or visit <a href=\"https://plum-support.xoxoday.com/support/home\">https://plum-support.xoxoday.com/support/home</a></div><div>&nbsp;</div>",
            "categories": "Books_Magazines & Subscriptions",
            "lastUpdateDate": "2022-10-06 14:22:46",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phphqmsKP_cnwezt.jpg",
            "currencyCode": "INR",
            "currencyName": "rupees",
            "countryName": "India",
            "countryCode": "IN",
            "countries": [
              {
                "code": "IN",
                "name": "India"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "5.0000,10.0000,15.0000,20.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 13,
            "exchangeRate": 1,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 51124,
            "name": "59s UVC LED Sterilization",
            "description": "<p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">Keep Calm. Sterilize Anywhere.<br /><br />59S lets you take the superior sterilization that only UV-C can provide, anywhere and everywhere you go.<br /><br />Designed with power and portability in mind, most 59S units include a 2000 mAh powerbank that can be used in 15 full cycles of sterilization before recharging.<br /><br />And with its premium LED UVC bulbs that can achieve UVGI (Ultraviolet Germicidal Irradiation) in just 3 minutes, you can rest assured that you and your family are protected even on the go.<br /><br />59S UVC LED bulbs can last up to 10,000 hours of sterilization before needing to be replaced.<br /><br />So if you want to extend the safety of UVC sanitization outside your home, choose a 59s product that’s right for you and your lifestyle.</p><p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">It can be redeemed in Parenting Emporium headquarters in 29 1st Street, New Manila, Quezon City or Parenting Emporium stores. For list of store, you may visit:&nbsp;<a href=\"http://theparentingemporium.com/store/\">http://theparentingemporium.com/store/</a></p><p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">Enjoy your gift!</p><div>&nbsp;</div>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>1. The gift certificate is valid immediately after receiving it.</p><p>2. It can be redeemed in all of merchant and branches and can be used to pay for anything for sale in the store.</p><p>3. It has no expiry date, is non-refundable, non-convertible to cash, is for one time use only and cannot be used in conjunction with other promos or discounts.</p><p>4. Extra charges will apply to items purchased in excess of the value of the gift certificate.</p><p>5. The Merchant is responsible for the quality of their own products and services.</p><p>6. Merchant prices may change without prior notice and may be subject to additional charges.</p>",
            "expiryAndValidity": "<p>No Expiry</p>",
            "redemptionInstructions": "<p>Simply present the gift certificate in the form of an email or voucher PDF file through your Mobile Phone or a Printed copy to the Merchant and customer service/staff for validation, then enjoy your perfect gift!</p>",
            "categories": "Electronics",
            "lastUpdateDate": "2023-05-09 10:29:41",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpstNUaz_svq8s2.jpg",
            "currencyCode": "PHP",
            "currencyName": "Philippine Peso",
            "countryName": "Philippines",
            "countryCode": "PH",
            "countries": [
              {
                "code": "PH",
                "name": "Philippines"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "500.0000,1000.0000,1500.0000,2000.0000,3000.0000,4000.0000,5000.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 1.5,
            "exchangeRate": 1.48964799,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 53773,
            "name": "6thStreet",
            "description": "<p>6thStreet.com is a one-stop shop for style-conscious women, men and kids in Qatar. The fashion-savvy destination offers collections from over 200 international fashion brands such as Tommy Hilfiger, Dune London, Charles & Keith, ALDO, Naturalizer, Nine West, New Balance, Crocs, Birkenstock, Skechers, Levi’s, Aeropostale, Garage, Nike, Adidas, Adidas Originals, Rituals, and many more. The online fashion platform also provides free delivery, free returns, cash on delivery and the option for click and collect. Download the 6thStreet app for iOS and Android. Follow us on @shop6thstreet to stay updated with new launches and offers.</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p style=\"color: rgb(34, 34, 34); font-family: Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\">6thStreet is an online store. This eGift card has to be used at<span>&nbsp;</span><a class=\"new_plink plink\" href=\"https://en-qa.6thstreet.com/\" target=\"_blank\">https://en-qa.6thstreet.com/</a><span>&nbsp;</span>Only one voucher can be redeemed per transaction. To redeem this eGift card: Enter eGift code at check out under \"coupon code\" This eGift Card can only be used once to make a purchase. Any unused amount at the time of making a purchase will be forfeited. In case the transaction amount is more than the value contained in the eGift card, the balance amount can be paid through other payment methods, by the customer who redeems the eGift Card. This eGift card must be redeemed within 6 months from the purchase date. Expired eGift cards cannot be extended, exchanged or refunded. How to Redeem:</p><ol style=\"padding: 0px 40px; color: rgb(34, 34, 34); font-family: Arial, Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;\"><li>Visit<span>&nbsp;</span><a class=\"new_plink plink\" href=\"https://en-qa.6thstreet.com/\" target=\"_blank\">https://en-qa.6thstreet.com/</a><span>&nbsp;</span>Select your items and add to cart. Go to shopping cart and proceed. Enter the eGift card code or coupon code. Click 'CHECKOUT'</li></ol>",
            "expiryAndValidity": "",
            "redemptionInstructions": "",
            "categories": "Jewelry & Lifestyle",
            "lastUpdateDate": "2023-05-11 12:38:27",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpfsP6ud_vawmih.png",
            "currencyCode": "QAR",
            "currencyName": "Qatar Riyal",
            "countryName": "Qatar",
            "countryCode": "QA",
            "countries": [
              {
                "code": "QA",
                "name": "Qatar"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "50.0000,100.0000,200.0000,500.0000",
            "tatInDays": "0",
            "usageType": "online",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 2,
            "exchangeRate": 23.05381156,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 52717,
            "name": "6thStreet Oman",
            "description": "<p>6thStreet.com is a one-stop shop for style-conscious women, men and kids in the UAE, KSA, Kuwait, Oman & Bahrain. The fashion-savvy destination offers collections from over 200 international fashion brands such as Tommy Hilfiger, Dune London, Charles & Keith, ALDO, Naturalizer, Nine West, New Balance, Crocs, Birkenstock, Skechers, Levi’s, Aeropostale, Garage, Nike, Adidas, Adidas Originals, Rituals, and many more. The online fashion platform also provides free delivery, free returns, cash on delivery and the option for click and collect. Download the 6thStreet app for iOS and Android. Follow us on @shop6thstreet to stay updated with new launches and offers.</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>6thStreet is an online store. This eGift card has to be used at https://en-om.6thstreet.com/ To redeem this eGift card: Enter eGift code at check out under \"coupon code\" Only one voucher can be redeemed per transaction. This eGift Card can only be used once to make a purchase. Any unused amount at the time of making a purchase will be forfeited. In case the transaction amount is more than the value contained in the eGift card, the balance amount can be paid through other payment methods, by the customer who redeems the eGift Card. This eGift card must be redeemed within 6 months from the purchase date. Expired eGift cards cannot be extended, exchanged or refunded. How to Redeem:</p><ol><li>Visit <a class=\"new_plink plink\" href=\"https://en-om.6thstreet.com/\" target=\"_blank\"> https://en-om.6thstreet.com/</a> Select your items and add to cart. Go to shopping cart and proceed. Enter the eGift card code or coupon code. Click 'CHECKOUT'</li></ol>",
            "expiryAndValidity": "<p>6 Months</p>",
            "redemptionInstructions": "",
            "categories": "Jewelry & Lifestyle",
            "lastUpdateDate": "2023-05-20 13:11:14",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpHgbiTj_p8pmg8.png",
            "currencyCode": "OMR",
            "currencyName": "Omani Rial",
            "countryName": "Oman",
            "countryCode": "OM",
            "countries": [
              {
                "code": "OM",
                "name": "Oman"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "5.0000,10.0000,20.0000,50.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 2,
            "exchangeRate": 218.04016249,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 50668,
            "name": "6thStreet UAE",
            "description": "<p>6thStreet.com is a one-stop shop for style-conscious women, men and kids in the UAE, KSA, Kuwait, Oman & Bahrain. The fashion-savvy destination offers collections from over 200 international fashion brands such as Tommy Hilfiger, Dune London, Charles & Keith, ALDO, Naturalizer, Nine West, New Balance, Crocs, Birkenstock, Skechers, Levi’s, Aeropostale, Garage, Nike, Adidas, Adidas Originals, Rituals, and many more. The online fashion platform also provides free delivery, free returns, cash on delivery and the option for click and collect. Download the 6thStreet app for iOS and Android. Follow us on @shop6thstreet to stay updated with new launches and offers.</p>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>6thStreet is an online store. This eGift card has to be used at https://en-ae.6thstreet.com/ To redeem this eGift card: Enter eGift code at check out under \"coupon code\" This eGift Card can only be used once to make a purchase. Any unused amount at the time of making a purchase will be forfeited. In case the transaction amount is more than the value contained in the eGift card, the balance amount can be paid through other payment methods, by the customer who redeems the eGift Card. This eGift card must be redeemed within 12 months from the purchase date. Expired eGift cards cannot be extended, exchanged or refunded.</p>",
            "expiryAndValidity": "<p>12 Months</p>",
            "redemptionInstructions": "<p>Avail vouche at&nbsp;6thStreet store.</p>",
            "categories": "Jewelry & Lifestyle",
            "lastUpdateDate": "2023-03-31 07:03:22",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpfzl2Yq_zwa1rr.png",
            "currencyCode": "AED",
            "currencyName": "UAE dirham",
            "countryName": "UAE",
            "countryCode": "AE",
            "countries": [
              {
                "code": "AE",
                "name": "UAE"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "50.0000,100.0000,200.0000,500.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 0,
            "exchangeRate": 22.85393357,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          },
          {
            "productId": 48026,
            "name": "7-Eleven",
            "description": "<p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">You can now give the gift of convenience with the 7-Eleven electronic gift card! The value of the gift card will be credited into your CLIQQ mobile wallet which can be used to pay for physical goods at any 7-Eleven and earn points as you spend.&nbsp; You can also&nbsp;use your wallet credits to purchase at CLiQQgrocery.com and pick-up your products at your selected 7-Eleven branch.</p><p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">Using CLiQQ and enjoying its benefits is easy and gratifying.&nbsp; The app includes a loyalty barcode that lets 7-Eleven customers earn points every time they make purchases worth P50 or more. On top of this, if they use their CLiQQ Wallet to pay, they earn 2x more points! That’s 1pt for every P25 spend in physical goods. These points can then be used to redeem items from the CLiQQ Rewards Catalog or at CLiQQgrocery.com, which includes a wide array of products.&nbsp; Customers can even share their points with friends, letting them have their pick of rewards as well.</p><p style=\"caret-color: rgb(34, 34, 34); text-size-adjust: auto;\">The CLiQQ mobile app also enables customers to know more about 7-Eleven’s latest promos and offers via the News & Promos tab. They can also share suggestions and comments about the app using the Send Feedback menu.&nbsp;</p><div>&nbsp;</div>",
            "orderQuantityLimit": 10,
            "termsAndConditionsInstructions": "<p>1. Gifted.PH will verify all orders before processing.&nbsp;</p><p>2. The gift certificate is valid immediately after receiving it.&nbsp;</p><p>3. It can be redeemed in all the merchant's branches and can be used to pay for any physical good in the store.</p><p>4. It has no expiry date, is non-refundable, non-convertible to cash, but can be used in conjunction with other promos or discounts.</p><p>5. Extra charges will apply to items purchased in excess of the value of the gift certificate.&nbsp;</p><p>6. Both Gifted.PH and the merchant are not responsible for the lost or stolen gift certificate.&nbsp;</p><p>7. The Merchant is responsible for the quality of their own products and services.&nbsp;</p><p>8. By using this electronic gift, you acknowledge and agree to the terms and conditions of CLiQQ, including its Data Privacy Policy. One (1) eWallet Credit = PHP 1.00.&nbsp;</p><p>9. eWallet credits have no expiry. No refund for unused credits.</p><p>voucher will be delivered within 5 to 6 working days</p>",
            "expiryAndValidity": "<p>No Expiry</p>",
            "redemptionInstructions": "<p>1. Go to <a href=\"https://www.cliqq.net/app/\">www.cliqq.net/app/</a> to download the latest version of the CLiQQ Mobile App.&nbsp;</p><p>2. Log in to the app with your mobile number, enter the verification code sent via SMS and agree to the terms and conditions.&nbsp;</p><p>3. To activate CLiQQ Wallet, click Open Wallet > Enter Email Address & Create a PIN.&nbsp;</p><p>4. To load the value of the Gift Card to CLiQQ Wallet, click Load Wallet > Redeem Code > and Type in the Redemption Code.&nbsp;</p><p>5. You can use your CLiQQ Wallet to pay for any merchandise inside any 7 Eleven store nationwide by opening the CLiQQ app, click \"Open Wallet\", Buy 7 Eleven, Enter Pin then cashier will scan the barcode. Done!</p>",
            "categories": "Restaurants Foods and Drinks",
            "lastUpdateDate": "2023-05-09 10:49:33",
            "imageUrl": "https://res.cloudinary.com/dyyjph6kx/image/upload/fl_lossy,f_auto,q_auto,h_280,w_420,c_fill/gift_vouchers/phpvbh20f_qka6ee.png",
            "currencyCode": "PHP",
            "currencyName": "Philippine Peso",
            "countryName": "Philippines",
            "countryCode": "PH",
            "countries": [
              {
                "code": "PH",
                "name": "Philippines"
              }
            ],
            "valueType": "fixed_denomination",
            "maxValue": 0,
            "minValue": 0,
            "valueDenominations": "100.0000,250.0000,300.0000,500.0000,1000.0000",
            "tatInDays": "0",
            "usageType": "",
            "deliveryType": "realtime",
            "fee": 0,
            "discount": 1,
            "exchangeRate": 1.48964799,
            "isPhoneNumberMandatory": false,
            "isRecommended": null
          }
        ]
  
  export default products;
  